/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.mainapp;

import controllers.MedicineController;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Medicine;

/**
 *
 * @author debuayanri_sd2022
 */
public class PhamControlMed extends javax.swing.JFrame {

    MedicineController mdc = new MedicineController();

    /**
     * Creates new form PharmacistMedicineOption
     */
    public PhamControlMed() {
        initComponents();
        ImageIcon icon = new ImageIcon("C:\\Users\\debuayanri_sd2022\\Desktop\\RCDMed_App\\src\\asset\\pharma.png");
        imageLabel.setIcon(icon);
        mdc.getAllMed(tblProduct);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bDelete1 = new javax.swing.JButton();
        bBack = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        viewCustomer = new javax.swing.JButton();
        viewMed = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        imageLabel = new javax.swing.JLabel();
        pharmacistID = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        logOut = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProduct = new javax.swing.JTable();
        bAdd = new javax.swing.JButton();
        bUpdate = new javax.swing.JButton();
        bReset = new javax.swing.JButton();
        bDelete2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        drug_id = new javax.swing.JTextField();
        drugCategory = new javax.swing.JLabel();
        category = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        drug_price = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        brand_name = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        drug_stock = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        IMessage = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        generic_name = new javax.swing.JTextField();
        expiration_date = new javax.swing.JTextField();
        drug_name = new javax.swing.JTextField();
        manufacturer = new javax.swing.JTextField();
        manufactured_date = new javax.swing.JTextField();
        pharmacistName = new javax.swing.JLabel();

        bDelete1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bDelete1.setText("DELETE");
        bDelete1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDelete1ActionPerformed(evt);
            }
        });

        bBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bBack.setText("BACK");
        bBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bBackMouseClicked(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Java Pharmacy - - - Control Medicines");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        viewCustomer.setBackground(new java.awt.Color(204, 255, 255));
        viewCustomer.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        viewCustomer.setText("View Customers");
        viewCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCustomerActionPerformed(evt);
            }
        });

        viewMed.setBackground(new java.awt.Color(204, 255, 255));
        viewMed.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        viewMed.setText("View Medicines");
        viewMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewMedActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(204, 255, 255));
        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton5.setText("Control Medicines");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        imageLabel.setBackground(new java.awt.Color(255, 204, 204));
        imageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pharmacistID.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pharmacistID.setText("ID: PhD-SD2022-0");

        jButton4.setBackground(new java.awt.Color(204, 255, 255));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton4.setText("Customer Orders");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        logOut.setBackground(new java.awt.Color(204, 255, 255));
        logOut.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        logOut.setText("Log Out");
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblProduct.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        tblProduct.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tblProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DRUG ID", "DRUG NAME", "GENERIC NAME", "BRAND NAME", "DRUG STOCK", "DRUG PRICE", "EXPIRATION DATE", "MANUFACTURED DATE", "MANUFACTURER", "CATEGORY"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblProduct);

        bAdd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bAdd.setText("ADD");
        bAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddActionPerformed(evt);
            }
        });

        bUpdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bUpdate.setText("UPDATE");
        bUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUpdateActionPerformed(evt);
            }
        });

        bReset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bReset.setText("RESET");
        bReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResetActionPerformed(evt);
            }
        });

        bDelete2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bDelete2.setText("DELETE");
        bDelete2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bDelete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDelete2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Drug ID:");

        drugCategory.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        drugCategory.setText("Category:");

        category.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "allergy", "body pain", "cough", "headache", "stomachache", "others" }));
        category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Drug Price:");

        drug_price.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Brand Name:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Drug Stock:");

        drug_stock.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Manufacturer:");

        IMessage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        IMessage.setForeground(new java.awt.Color(207, 0, 15));
        IMessage.setText("........");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Expiration Date:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Manufactured Date:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Generic Name:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Drug Name:");

        generic_name.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        expiration_date.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        drug_name.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        manufacturer.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        manufactured_date.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(59, 59, 59))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(29, 29, 29)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(drug_name, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                            .addComponent(drug_id)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(drugCategory))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(manufacturer, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(manufactured_date, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(expiration_date, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(category, 0, 317, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel11)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(drug_stock, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                            .addComponent(generic_name, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(brand_name, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(drug_price)))
                    .addComponent(IMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(bAdd)
                        .addGap(18, 18, 18)
                        .addComponent(bUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bDelete2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1026, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(drug_id, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(drug_name, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15)
                            .addComponent(generic_name, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(brand_name, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(drug_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(drug_price, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(expiration_date, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(manufactured_date, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(manufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(drugCategory)
                            .addComponent(category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bAdd)
                            .addComponent(bUpdate)
                            .addComponent(bReset)
                            .addComponent(bDelete2)))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        pharmacistName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pharmacistName.setText("FirstName M. LastName,Pharm.D.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pharmacistID, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                        .addComponent(viewCustomer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pharmacistName, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewMed, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logOut, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pharmacistName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pharmacistID, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(viewMed, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logOut, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Goodbye!");
        this.dispose();
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

    }//GEN-LAST:event_logOutActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton5ActionPerformed

    private void viewMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewMedActionPerformed
        // TODO add your handling code here:
        PhamViewMed cm = new PhamViewMed();
        cm.pharmacistName.setText(pharmacistName.getText());
        cm.pharmacistID.setText(pharmacistID.getText());
        cm.setVisible(true);
        this.dispose();
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_viewMedActionPerformed

    private void tblProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductMouseClicked

        DefaultTableModel model = (DefaultTableModel) tblProduct.getModel();
        drug_id.setText(model.getValueAt(tblProduct.getSelectedRow(), 0).toString());
        drug_name.setText(model.getValueAt(tblProduct.getSelectedRow(), 1).toString());
        generic_name.setText(model.getValueAt(tblProduct.getSelectedRow(), 2).toString());
        brand_name.setText(model.getValueAt(tblProduct.getSelectedRow(), 3).toString());
        drug_stock.setText(model.getValueAt(tblProduct.getSelectedRow(), 4).toString());
        drug_price.setText(model.getValueAt(tblProduct.getSelectedRow(), 5).toString());
        expiration_date.setText(model.getValueAt(tblProduct.getSelectedRow(), 6).toString());
        manufactured_date.setText(model.getValueAt(tblProduct.getSelectedRow(), 7).toString());
        manufacturer.setText(model.getValueAt(tblProduct.getSelectedRow(), 8).toString());
        category.setSelectedItem(model.getValueAt(tblProduct.getSelectedRow(), 9).toString());
        drug_id.disable();

    }//GEN-LAST:event_tblProductMouseClicked

    private void bAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddActionPerformed
        drug_id.enable();
        int total = 0;
        int sum = 0;

        DefaultTableModel model = (DefaultTableModel) tblProduct.getModel();
        try {
            if (!drug_id.getText().trim().equals("") && !drug_name.getText().trim().equals("") && !generic_name.getText().trim().equals("") && !brand_name.getText().trim().equals("") && !drug_stock.getText().trim().equals("") && !drug_price.getText().trim().equals("") && !expiration_date.getText().trim().equals("") && !manufactured_date.getText().trim().equals("") && !manufacturer.getText().trim().equals("")) {
                Medicine m = new Medicine(drug_id.getText(), drug_name.getText(), generic_name.getText(), brand_name.getText(), Integer.parseInt(drug_stock.getText()), Double.parseDouble(drug_price.getText()), expiration_date.getText(), manufactured_date.getText(), manufacturer.getText(), category.getSelectedItem().toString());
                mdc.addMed(m, drug_id.getText(), this);
                model.addRow(new Object[]{drug_id.getText(), drug_name.getText(), generic_name.getText(), brand_name.getText(), Integer.parseInt(drug_stock.getText()), Double.parseDouble(drug_price.getText()), expiration_date.getText(), manufactured_date.getText(), manufacturer.getText(), category.getSelectedItem().toString()});
            } else {
                IMessage.setText("Inputs Should not be left blank");
            }
        } catch (Exception e) {
            IMessage.setText("Make sure you input the correct data types.");
            System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_bAddActionPerformed

    private void bUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUpdateActionPerformed
        drug_id.disable();
        DefaultTableModel model = (DefaultTableModel) tblProduct.getModel();
        if (tblProduct.getSelectedRow() == -1) {
            if (tblProduct.getRowCount() == 0) {
                IMessage.setText("Table is Empty.");
            } else {
                IMessage.setText("You must Selected a Product.");
            }
        } else {
            try {
                if (!drug_id.getText().trim().equals("") && !drug_name.getText().trim().equals("") && !generic_name.getText().trim().equals("") && !brand_name.getText().trim().equals("") && !drug_stock.getText().trim().equals("") && !drug_price.getText().trim().equals("") && !expiration_date.getText().trim().equals("") && !manufactured_date.getText().trim().equals("") && !manufacturer.getText().trim().equals("")) {
                    Medicine m = new Medicine(drug_id.getText(), drug_name.getText(), generic_name.getText(), brand_name.getText(), Integer.parseInt(drug_stock.getText()), Double.parseDouble(drug_price.getText()), expiration_date.getText(), manufactured_date.getText(), manufacturer.getText(), category.getSelectedItem().toString());
                    mdc.modifyMed(m);
                    model.setValueAt(drug_name.getText(), tblProduct.getSelectedRow(), 1);
                    model.setValueAt(generic_name.getText(), tblProduct.getSelectedRow(), 2);
                    model.setValueAt(brand_name.getText(), tblProduct.getSelectedRow(), 3);
                    model.setValueAt(Integer.parseInt(drug_stock.getText()), tblProduct.getSelectedRow(), 4);
                    model.setValueAt(Double.parseDouble(drug_price.getText()), tblProduct.getSelectedRow(), 5);
                    model.setValueAt(expiration_date.getText(), tblProduct.getSelectedRow(), 6);
                    model.setValueAt(manufactured_date.getText(), tblProduct.getSelectedRow(), 7);
                    model.setValueAt(manufacturer.getText(), tblProduct.getSelectedRow(), 8);
                    model.setValueAt(category.getSelectedItem().toString(), tblProduct.getSelectedRow(), 9);
                } else {
                    IMessage.setText("Inputs Should not be left blank");
                }
            } catch (Exception e) {
                IMessage.setText("Make sure you input the correct data types.");
                System.err.println(e.getMessage());
            }

        }

    }//GEN-LAST:event_bUpdateActionPerformed

    private void bResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResetActionPerformed
        drug_id.enable();
        drug_id.setText(null);
        drug_name.setText(null);
        generic_name.setText(null);
        brand_name.setText(null);
        drug_stock.setText(null);
        drug_price.setText(null);
        expiration_date.setText(null);
        manufactured_date.setText(null);
        manufacturer.setText(null);
        category.setSelectedItem(null);
    }//GEN-LAST:event_bResetActionPerformed

    private void bDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDelete1ActionPerformed

    }//GEN-LAST:event_bDelete1ActionPerformed

    private void bDelete2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDelete2ActionPerformed
        drug_id.disable();
        DefaultTableModel model = (DefaultTableModel) tblProduct.getModel();
        if (tblProduct.getSelectedRow() == -1) {
            if (tblProduct.getRowCount() == 0) {
                IMessage.setText("Table is Empty.");
            } else {
                IMessage.setText("You must Selected a Product.");
            }
        } else {
            String id = model.getValueAt(tblProduct.getSelectedRow(), 0).toString();
            mdc.delMed(id);
            model.removeRow(tblProduct.getSelectedRow());
        }
    }//GEN-LAST:event_bDelete2ActionPerformed

    private void bBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bBackMouseClicked

        this.dispose();
    }//GEN-LAST:event_bBackMouseClicked

    private void categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryActionPerformed

    private void viewCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCustomerActionPerformed
        // TODO add your handling code here:
        PhamViewCustomer cm = new PhamViewCustomer();
        cm.pharmacistName.setText(pharmacistName.getText());
        cm.pharmacistID.setText(pharmacistID.getText());
        cm.setVisible(true);
        this.dispose();
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_viewCustomerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhamControlMed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhamControlMed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhamControlMed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhamControlMed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PhamControlMed().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IMessage;
    private javax.swing.JButton bAdd;
    private javax.swing.JButton bBack;
    private javax.swing.JButton bDelete1;
    private javax.swing.JButton bDelete2;
    private javax.swing.JButton bReset;
    private javax.swing.JButton bUpdate;
    private javax.swing.JTextField brand_name;
    private javax.swing.JComboBox<String> category;
    private javax.swing.JLabel drugCategory;
    private javax.swing.JTextField drug_id;
    private javax.swing.JTextField drug_name;
    private javax.swing.JTextField drug_price;
    private javax.swing.JTextField drug_stock;
    private javax.swing.JTextField expiration_date;
    private javax.swing.JTextField generic_name;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton logOut;
    private javax.swing.JTextField manufactured_date;
    private javax.swing.JTextField manufacturer;
    public javax.swing.JLabel pharmacistID;
    public javax.swing.JLabel pharmacistName;
    public javax.swing.JTable tblProduct;
    private javax.swing.JButton viewCustomer;
    private javax.swing.JButton viewMed;
    // End of variables declaration//GEN-END:variables
}
